<?php
$statusLabel = static fn (string $status): string => ucwords(str_replace('_', ' ', $status));
$terminal = in_array($order['status'], ['completed','cancelled','expired','refunded'], true);
?>
<div class="d-flex justify-content-between align-items-start gap-3 mb-4">
    <div>
        <p class="text-uppercase fw-semibold archive-kicker-dark mb-1"><?= $isBuyer ? 'Purchase' : 'Sale' ?></p>
        <h1 class="h2 mb-2">Order #<?= e((string) $order['id']) ?></h1>
        <span class="badge text-bg-light"><?= e($statusLabel($order['status'])) ?></span>
        <span class="badge text-bg-info">Payment: <?= e($statusLabel($order['payment_status'])) ?></span>
        <span class="badge text-bg-secondary">Fulfillment: <?= e($statusLabel($order['fulfillment_status'])) ?></span>
    </div>
    <a class="btn btn-outline-secondary" href="<?= e(url($isBuyer ? '/orders' : '/orders/sales')) ?>">Back to orders</a>
</div>

<div class="row g-4"><div class="col-lg-8">
    <div class="archive-card p-4 mb-4"><h2 class="h5">Items</h2>
        <?php foreach ($items as $item): ?><div class="d-flex justify-content-between border-bottom py-2"><div><strong><?= e($item['card_name']) ?></strong><div class="small text-muted"><?= e($item['set_name']) ?> #<?= e($item['collector_number']) ?> | <?= e(ucwords(str_replace('_',' ', $item['card_condition']))) ?> | Qty <?= e((string) $item['quantity']) ?></div></div><div>PHP <?= e(number_format((float) $item['line_total_php'], 2)) ?></div></div><?php endforeach; ?>
    </div>

    <div class="archive-card p-4 mb-4"><h2 class="h5">Fulfillment</h2><dl class="row mb-0"><dt class="col-sm-4">Method</dt><dd class="col-sm-8"><?= e($order['logistics_method'] === 'lbc' ? 'LBC shipping' : 'Meetup') ?></dd><dt class="col-sm-4">Details</dt><dd class="col-sm-8"><?= e($order['delivery_preference']) ?></dd><?php if (!empty($order['tracking_reference'])): ?><dt class="col-sm-4">Tracking</dt><dd class="col-sm-8"><?= e($order['tracking_carrier']) ?> | <?= e($order['tracking_reference']) ?></dd><?php endif; ?><?php if (!empty($order['settlement_available_at']) && $order['status'] === 'delivered'): ?><dt class="col-sm-4">Auto-settlement</dt><dd class="col-sm-8"><?= e($order['settlement_available_at']) ?> unless disputed</dd><?php endif; ?></dl></div>

    <div class="archive-card p-4 mb-4"><h2 class="h5">Payment proofs</h2>
        <?php if ($paymentProofs === []): ?><p class="text-muted mb-0">No payment proof uploaded.</p><?php else: ?>
        <?php foreach ($paymentProofs as $proof): ?><div class="border rounded p-3 mb-2"><div class="d-flex justify-content-between gap-2"><div><strong>Proof #<?= e((string) $proof['id']) ?></strong> <span class="badge text-bg-light"><?= e(ucfirst($proof['status'])) ?></span><div class="small text-muted"><?= e($proof['created_at']) ?> | <?= e(number_format((int) $proof['file_size'] / 1024, 1)) ?> KB</div></div><a class="btn btn-sm btn-outline-dark" target="_blank" rel="noopener" href="<?= e(url('/payment-proofs/view?id=' . (int) $proof['id'])) ?>">View image</a></div>
            <?php if (!empty($proof['review_notes'])): ?><div class="small mt-2">Review: <?= e($proof['review_notes']) ?></div><?php endif; ?>
            <?php if ($isSeller && $proof['status'] === 'pending' && $order['status'] === 'payment_submitted'): ?><div class="row g-2 mt-2"><div class="col-md-6"><form method="post" action="<?= e(url('/payment-proofs/review?id=' . (int) $proof['id'])) ?>"><input type="hidden" name="decision" value="approve"><button class="btn btn-sm btn-success w-100">Approve proof</button></form></div><div class="col-md-6"><form method="post" action="<?= e(url('/payment-proofs/review?id=' . (int) $proof['id'])) ?>"><input type="hidden" name="decision" value="reject"><input class="form-control form-control-sm mb-2" name="review_notes" minlength="5" maxlength="1000" placeholder="Reason for rejection" required><button class="btn btn-sm btn-outline-danger w-100">Reject proof</button></form></div></div><?php endif; ?>
        </div><?php endforeach; ?><?php endif; ?>
    </div>

    <div class="archive-card p-4 mb-4"><h2 class="h5">Order messages</h2><p class="small text-muted">Messages are visible only to the buyer and seller. Attachments are disabled.</p><div class="mb-3"><?php if ($messages === []): ?><p class="text-muted">No messages yet.</p><?php else: ?><?php foreach ($messages as $message): ?><div class="border rounded p-2 mb-2 <?= (int) $message['sender_id'] === (int) current_user()['id'] ? 'ms-md-5 bg-light' : 'me-md-5' ?>"><div class="small fw-semibold"><?= e($message['sender_username']) ?> <span class="text-muted fw-normal"><?= e($message['created_at']) ?></span></div><div><?= nl2br(e($message['body'])) ?></div><?php if ((int) $message['sender_id'] === (int) current_user()['id']): ?><div class="small text-muted"><?= ($isBuyer ? !empty($message['seller_read_at']) : !empty($message['buyer_read_at'])) ? 'Read' : 'Sent' ?></div><?php endif; ?></div><?php endforeach; ?><?php endif; ?></div><?php if (!$terminal): ?><form method="post" action="<?= e(url('/orders/messages?order_id=' . (int) $order['id'])) ?>"><label class="form-label" for="message_body">Message</label><textarea class="form-control" id="message_body" name="body" maxlength="2000" rows="3" required></textarea><button class="btn btn-archive mt-2">Send message</button></form><?php endif; ?></div>

    <div class="archive-card p-4"><h2 class="h5">Order timeline</h2><?php foreach ($history as $event): ?><div class="border-start border-2 ps-3 pb-3"><strong><?= e($statusLabel($event['to_status'])) ?></strong><div class="small text-muted"><?= e($event['created_at']) ?><?= !empty($event['changed_by_username']) ? ' | ' . e($event['changed_by_username']) : ' | System' ?></div><?php if (!empty($event['note'])): ?><div class="small"><?= e($event['note']) ?></div><?php endif; ?></div><?php endforeach; ?></div>
</div>

<div class="col-lg-4">
    <div class="archive-card p-4 mb-4"><h2 class="h5">Payment summary</h2><dl class="row mb-0"><dt class="col-7">Subtotal</dt><dd class="col-5 text-end">PHP <?= e(number_format((float) $order['subtotal_php'], 2)) ?></dd><dt class="col-7">Logistics</dt><dd class="col-5 text-end">PHP <?= e(number_format((float) $order['logistics_fee_php'], 2)) ?></dd><dt class="col-7">Store credit</dt><dd class="col-5 text-end">-PHP <?= e(number_format((float) $order['store_credit_used'], 2)) ?></dd><dt class="col-7">Cash due</dt><dd class="col-5 text-end fw-bold">PHP <?= e(number_format((float) $order['cash_amount_due'], 2)) ?></dd></dl><?php if (!empty($order['payment_reference'])): ?><hr><div class="small"><strong><?= e($order['external_payment_method']) ?></strong><br>Reference: <?= e($order['payment_reference']) ?></div><?php endif; ?><?php if ($order['status'] === 'pending_payment'): ?><div class="alert alert-warning mt-3 mb-0 small">Payment deadline: <?= e($order['payment_deadline']) ?></div><?php endif; ?></div>

    <?php if (!$terminal): ?><div class="archive-card p-4"><h2 class="h5">Available actions</h2>
        <?php if ($isBuyer && $order['status'] === 'pending_payment'): ?><form method="post" enctype="multipart/form-data" action="<?= e(url('/payment-proofs/upload?order_id=' . (int) $order['id'])) ?>"><div class="mb-2"><label class="form-label small">Payment method</label><input class="form-control" name="external_payment_method" maxlength="80" value="<?= e($order['external_payment_method']) ?>" required></div><div class="mb-2"><label class="form-label small">Payment reference</label><input class="form-control" name="payment_reference" maxlength="150" required></div><div class="mb-2"><label class="form-label small">Payment proof image</label><input class="form-control" type="file" name="payment_proof" accept="image/jpeg,image/png,image/webp" required><div class="form-text">JPEG, PNG, or WebP; maximum 5 MB.</div></div><button class="btn btn-archive w-100">Submit payment proof</button></form><?php endif; ?>
        <?php if ($isSeller && $order['status'] === 'payment_verified'): ?><form method="post" action="<?= e(url('/orders/status?id=' . (int) $order['id'])) ?>"><input type="hidden" name="status" value="<?= e($order['logistics_method'] === 'lbc' ? 'preparing' : 'ready_for_meetup') ?>"><button class="btn btn-archive w-100"><?= $order['logistics_method'] === 'lbc' ? 'Start preparing shipment' : 'Ready for meetup' ?></button></form><?php endif; ?>
        <?php if ($isSeller && $order['status'] === 'preparing' && $order['logistics_method'] === 'lbc'): ?><form method="post" action="<?= e(url('/orders/tracking?id=' . (int) $order['id'])) ?>"><div class="mb-2"><label class="form-label small">Carrier</label><input class="form-control" name="tracking_carrier" maxlength="80" value="LBC" required></div><div class="mb-2"><label class="form-label small">Tracking reference</label><input class="form-control" name="tracking_reference" maxlength="150" required></div><button class="btn btn-archive w-100">Mark shipped</button></form><?php endif; ?>
        <?php if ($isBuyer && in_array($order['status'], ['shipped','ready_for_meetup'], true)): ?><form method="post" action="<?= e(url('/orders/status?id=' . (int) $order['id'])) ?>"><input type="hidden" name="status" value="delivered"><button class="btn btn-archive w-100">Mark received</button></form><?php endif; ?>
        <?php if ($isBuyer && $order['status'] === 'delivered'): ?><form method="post" action="<?= e(url('/orders/status?id=' . (int) $order['id'])) ?>"><input type="hidden" name="status" value="buyer_confirmed"><button class="btn btn-archive w-100">Confirm order is correct</button></form><?php endif; ?>
        <?php if ($isSeller && $order['status'] === 'buyer_confirmed'): ?><form method="post" action="<?= e(url('/orders/status?id=' . (int) $order['id'])) ?>"><input type="hidden" name="status" value="completed"><button class="btn btn-archive w-100">Complete order</button></form><?php endif; ?>
        <?php if ($order['status'] === 'pending_payment'): ?><hr><form method="post" action="<?= e(url('/orders/status?id=' . (int) $order['id'])) ?>" onsubmit="return confirm('Cancel this order and restore inventory?');"><input type="hidden" name="status" value="cancelled"><button class="btn btn-outline-danger w-100">Cancel order</button></form><?php endif; ?>
    </div><?php endif; ?>
</div></div>

<?php if ($disputes !== []): ?><div class="archive-card p-4 mt-4"><h2 class="h5">Dispute history</h2><?php foreach ($disputes as $dispute): ?><div class="border rounded p-3 mb-2"><div><strong>Dispute #<?= e((string) $dispute['id']) ?></strong> <span class="badge text-bg-<?= $dispute['status'] === 'resolved' ? 'success' : 'warning' ?>"><?= e(ucfirst($dispute['status'])) ?></span></div><div class="small text-muted"><?= e(ucwords(str_replace('_', ' ', $dispute['reason']))) ?> · opened by <?= e($dispute['opener_username']) ?> · <?= e($dispute['created_at']) ?></div><?php if ($dispute['status'] === 'resolved'): ?><div class="small mt-2"><strong>Resolution:</strong> <?= e(ucwords(str_replace('_', ' ', $dispute['resolution']))) ?><?php if ((float) $dispute['refund_total'] > 0): ?> · PHP <?= e(number_format((float) $dispute['refund_total'], 2)) ?> refunded<?php endif; ?><br><?= nl2br(e($dispute['resolution_notes'])) ?></div><?php endif; ?></div><?php endforeach; ?></div><?php endif; ?>

<div class="row g-4 mt-0">
<?php if ($activeDispute === null && in_array($order['status'], ['payment_verified','preparing','shipped','ready_for_meetup','delivered','buyer_confirmed','completed'], true)): ?><div class="col-lg-6"><div class="archive-card p-4 h-100"><h2 class="h5">Something went wrong?</h2><p class="small text-muted">Opening a dispute freezes settlement while an administrator reviews the order evidence.</p><a class="btn btn-outline-danger" href="<?= e(url('/disputes/create?order_id=' . (int) $order['id'])) ?>">Open a dispute</a></div></div><?php endif; ?>
<?php if ($isBuyer && $order['status'] === 'completed'): ?><div class="col-lg-6"><div class="archive-card p-4 h-100"><h2 class="h5">Verified purchase review</h2><?php if ($review !== null): ?><div class="mb-2" aria-label="<?= e((string) $review['rating']) ?> out of 5 stars"><?= e(str_repeat('★', (int) $review['rating'])) ?><?= e(str_repeat('☆', 5 - (int) $review['rating'])) ?></div><p class="mb-0"><?= nl2br(e($review['body'])) ?></p><?php else: ?><form method="post" action="<?= e(url('/reviews/store?order_id=' . (int) $order['id'])) ?>"><label class="form-label" for="rating">Rating</label><select class="form-select mb-2" id="rating" name="rating" required><option value="">Choose rating</option><?php for ($stars = 5; $stars >= 1; $stars--): ?><option value="<?= $stars ?>"><?= $stars ?> star<?= $stars === 1 ? '' : 's' ?></option><?php endfor; ?></select><label class="form-label" for="review_body">Review</label><textarea class="form-control" id="review_body" name="body" minlength="10" maxlength="2000" rows="4" required></textarea><button class="btn btn-archive mt-2">Publish review</button></form><?php endif; ?></div></div><?php endif; ?>
</div>
